apiVersion: triggers.tekton.dev/v1beta1
kind: EventListener
metadata:
  name: listener
spec:
  serviceAccountName: tekton-robot
  triggers:
    - name: trigger 
      bindings:
      - ref: binding
      template:
        ref: template
        