apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: binding
spec: 
  params:
    - name: image_tag
      value: $(body.data.image_tag)
    - name: repo_url
      value: $(body.data.repo_url)
    - name: image_name
      value: $(body.data.image_name)
    - name: dockerfile_path
      value: $(body.data.dockerfile_path)
    - name: dockerfile_context
      value: $(body.data.dockerfile_context)
    - name: application_name
      value: $(body.data.application_name)
    - name: manifest_repo
      value: $(body.data.manifest_repo)
    - name: manifest_path
      value: $(body.data.manifest_path)
    - name: git_email
      value: $(body.data.git_email)
    - name: git_username
      value: $(body.data.git_username)
    - name: branch_name
      value: $(body.data.branch_name)
    - name: namespace
      value: $(body.data.@namespace)
    - name: deployment_name
      value: $(body.data.deployment_name)
    - name: deployment_label
      value: $(body.data.deployment_label)
    - name: image_registry
      value: $(body.data.image_registry)
    - name: image_path
      value: $(body.data.image_path)
    - name: container_port
      value: $(body.data.container_port)
    - name: resources_request_memory
      value: $(body.data.resources.request_memory)
    - name: resources_request_cpu
      value: $(body.data.resources.request_cpu)
    - name: resources_limit_memory
      value: $(body.data.resources.limit_memory)
    - name: resources_limit_cpu
      value: $(body.data.resources.limit_cpu)
    - name: min_replicas
      value: $(body.data.autoscaling.min_replicas)
    - name: max_replicas
      value: $(body.data.autoscaling.max_replicas)
    - name: cpu_average_utilization
      value: $(body.data.autoscaling.cpu_average_utilization)
    - name: memory_average_utilization
      value: $(body.data.autoscaling.memory_average_utilization)
    - name: vault_token
      value: $(body.data.vault_token)
    - name: apisix_url
      value: $(body.data.apisix.url)
    - name: apisix_admin_api_key
      value: $(body.data.apisix.admin_api_key)
    - name: apisix_upstream_name
      value: $(body.data.apisix.upstream_name)
    - name: apisix_service_name
      value: $(body.data.apisix.service_name)
    - name: apisix_route_name
      value: $(body.data.apisix.route_name)
    - name: apisix_route_host
      value: $(body.data.apisix.route_host)
    - name: backend_svc_name
      value: $(body.data.apisix.backend_svc_name)
    - name: backend_svc_port
      value: $(body.data.apisix.backend_svc_port)
    - name: devopszon_agent_url
      value: $(body.data.devopszon_agent_url)
    - name: configuration_items_json
      value: $(body.data.configuration_items_json)